package exception;

public class Throw {
	public static void main(String[] args) {
		int i,j;
		i=8;
		j=2;
		try
		{
		  int k=i/j;
		  System.out.println(k);
			
		}
		catch(Exception e)
		{
			System.out.println("Divided By zero.");
		}
		
	}

}
