package exception;

public class OneTryMultipleCatch {
	public static void main(String[] args) {
		int i,j=8,k=0;
		try
		{
			i=j/k;
		}
		catch(ArithmeticException e)
		{
			System.out.println("Divided by zero.");
			//e.printStackTrace();
		}
		System.out.println("The value of j:"+j);
	}

}
