package exception;

public class Throw {
	public static void main(String[] args) {
		int i=0,j=8,k=9;
		try
		{
			i=j/k;
			
		}
		catch(Exception e)
		{
			System.out.println("Divided By zero.");
		}
		System.out.println(i);
	}

}
